name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Check format
        run: npm run format-check

      - name: Run tests
        run: npm run test
