name: CI
on:
  push:
    branches: [master]

jobs:
  validate:
    name: Validate code quality
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      - name: Check format
        run: npm format-check

      # Step 2:
      - name: Run tests
        run: npm test
